### ISSUE TITLE
Compiling failed. not mathching declaration for par::PartitionMgr::partitionDesign

### ISSUE THREAD

**Issue by flwave** [ABKGroup/TritonPart#2]
Hi, I'm trying to build TritonPart. After successfully using cmake to generate the files, during runtimg make, it says 

...TritonPart/OpenROAD/src/par/src/PartitionMgr.cpp:1400:6: error: no declaration matches ‘void par::PartitionMgr::partitionDesign(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, bool, const char*, const char*, float, float, float, float)’
 1400 | void PartitionMgr::partitionDesign(unsigned int max_num_macro,
      |      ^~~~~~~~~~~~
...TritonPart/OpenROAD/src/par/src/PartitionMgr.cpp:1400:6: note: no functions named ‘void par::PartitionMgr::partitionDesign(unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, bool, const char*, const char*, float, float, float, float)’
In file included from .../TritonPart/OpenROAD/src/par/src/PartitionMgr.cpp:36:
.../TritonPart/OpenROAD/src/par/include/par/PartitionMgr.h:242:7: note: ‘class par::PartitionMgr’ defined here
  242 | class PartitionMgr
      |       ^~~~~~~~~~~~

Seems like this happened in OpenROAD library, but it's directly cloned from TritonPart repository. 
Any ideas about this error?
Thanks!

**Comment by ZhiangWang033** [comment]
@flwave ,   we have fixed this issue.  Please try again.

**Comment by flwave** [comment]
@ZhiangWang033 Thank you! Now we can complete the compiling without any error.

However, there's still some parts maybe we missed:
The tutorial in README indicates people can run the following command to test a demo
triton_part_hypergraph -hypergraph_file des90.hgr...
Besides, the python files to test the benchmark also need "triton_part_hypergraph" executable file.

But there is no such file (neither other executable files) in "bin" folder of "build". We also don't find any cmakefile that declare such a name "triton_part_hypergraph".
I attached some screenshots about the "build" folder, "build/bin" folder, and the last part of the compilation (after compiled successfully), not sure if they'll help.
Shall we ask if there's anything we missed? Thanks!

![Screenshot 2023-12-24 230315](https://github.com/ABKGroup/TritonPart/assets/22671934/15fe69c4-7971-4dd5-ab13-d4168cce0d26)
![Screenshot 2023-12-24 230326](https://github.com/ABKGroup/TritonPart/assets/22671934/6b11e7ec-11a3-466d-98fe-8cbc7cfaa30c)
![Screenshot 2023-12-24 230339](https://github.com/ABKGroup/TritonPart/assets/22671934/8d8e5f9f-4086-4f8f-a235-57eb75df4041)

**Comment by ZhiangWang033** [comment]
@flwave,  please check the updated README.md.

**Comment by flwave** [comment]
Now it works. Thx!
