### ISSUE TITLE
Stand-alone library version of TritonPart?

### ISSUE THREAD

**Issue by profmadden** [ABKGroup/TritonPart#5]
Hi -- wondering if there's a build script to generate a linkable library with just the partitioner.  I'd like to try swapping in and out hMetis, KaHyPar, and TritonPart into some of my tools.

For TritonPart, it looks like I need to link in a very large chunk of the OpenRoad project (spdlog, sta, odb, and likely more) to get things to compile and link.  Is there an easier way to do this, or a minimal set of other libraries that are required?

**Comment by bodhi91** [comment]
Hi Professor Madden

Unfortunately, TritonPart has several dependencies on OpenROAD infrastructure (OpenDB for reading a netlist, OpenSTA for timing). So they are inseparable at this point. The hypergraph partitioner (`triton_part_hypergraph`) can be conceptualized as a standalone partitioner by taking out the OpenROAD components and compiling the code separately. However, this does not exist yet. As a workaround, we can help you install OpenROAD / link the partitioner to your tool, should you face any difficulties doing that. 

Please let us know if we can do anything to help.

**Comment by profmadden** [comment]
Hi -- this was sort of what it looked like, but I wanted to check before doing things "the hard way."
I'll give a shout if I run into any big trouble, but I think I can track down the components needed to get it all to compile and run.

**Comment by ombhilare999** [comment]
Hi Professor @profmadden ,

I am also using TritonPart in a personal project. I can share my notes related to installing and using TritonPart. I hope this is helpful.

## Step 1: Dependency installation:

- Triton Part is a part of OpenRoad and has lots of dependencies with it.
- So, we will need to install all the dependencies of OpenRoad first.

```
git clone --recursive https://github.com/The-OpenROAD-Project/OpenROAD.git
cd OpenROAD
sudo ./etc/DependencyInstaller.sh
```

## Step 2: TritonPart Installation:

- Now that all the dependencies are resolved, we could install Triton_Part:
- [NOTE: Installation may take around 15-30 minutes!!]

```
git clone https://github.com/ombhilare999/TritonPart.git
cd TritonPart
mkdir build
cd build
cmake ../OpenROAD/
make
```

## Step 3: TritonPart testing:
```
cd TritonPart/test
../build/src/openroad run_openroad.tcl | tee run.log
```

- Output should look like this:

```
=========================================
[STATUS] Running FC multilevel coarsening
=========================================
[COARSEN] Level 0 :: num_vertices = 109, num_hyperedges = 111
[COARSEN] Level 1 :: num_vertices = 108, num_hyperedges = 110
[INFO PAR-0001] Hierarchical coarsening time 0.000294701 seconds
[Cutcost of partition : 525.0]
[Vertex balance of block_0 : 0.34596  ( 38478.00000 )
[Vertex balance of block_1 : 0.31945  ( 35529.00000 )
[Vertex balance of block_2 : 0.33460  ( 37214.00000 )
[Refinement] Level 1 :: num_vertices = 109, num_hyperedges = 111, cutcost = 525.0, best_solution_id = 0
[INFO PAR-0158] Statistics of cut-overlay solution:
[Cutcost of partition : 539.0]
[Vertex balance of block_0 : 0.34596  ( 38478.00000 )
[Vertex balance of block_1 : 0.31945  ( 35529.00000 )
[Vertex balance of block_2 : 0.33460  ( 37214.00000 )
[Cutcost of partition : 539.0]
[Vertex balance of block_0 : 0.34596  ( 38478.00000 )
[Vertex balance of block_1 : 0.31945  ( 35529.00000 )
[Vertex balance of block_2 : 0.33460  ( 37214.00000 )
Satisfy the balance constraint : true
Satisfy the group constraint : true
Satisfy the fixed vertices constraint : true
[INFO PAR-0109] The runtime of multi-level partitioner : 47.304750635000005 seconds
===============================================
Exiting TritonPart
```
